Chevrotain/chevrotain

examples/errorRecovery/sqlStatements/SqlRecoveryParser.ts
src/parse/GAstBuilder.ts
src/parse/Recognizer.ts

because:
A. It provides inconsistent API
there is a MANY_OR but not AT_LEAST_ONE_OR
B. It is used to reduce verbosity in the DSL. (nesting only OR inside MANY)
MANY(LA_FUNC, () => {
OR([
{WHEN:LA_FUNC1 THEN_DO:XXX},
{WHEN:LA_FUNC2 THEN_DO:YYY},
{WHEN:LA_FUNC3 THEN_DO:ZZZ}
...
]
})
but once all the LA_FUNCs can be computed automatically on the fly
it will look much more "pretty"
MANY(() => {
OR([
{ALT:XXX},
{ALT:YYY},
{ALT:ZZZ}
]})
C. The third reason for MANY_OR is performance optimizations.
to avoid checking the lookahead conditions twice.
once when entering the MANY and once when choosing the
alternative in the OR.
the counter argument for this is:
* make it pretty first and fast second.
* it could probably still be made fast by remembering the
result of the lookahead condition without …

removing MANY_OR DSL construct.

---

examples/ecmascript5/ecmascript5_tokens.ts

1. remove redundant comments
2. reword module notes.
3. remove unneeded token categories.

ECMA5 Tokens cleanup/upgrade.

---

src/scan/lexer.ts
test/scan/lexer_spec.ts

in SimpleLexer patterns.
This is not supported as the SimpleLexer works on matching
part of the input from the start for each token.

validation that detects "END OF INPUT" anchor

---

examples/ecmascript5/ecmascript5_parser.ts
src/parse/grammar/lookahead.ts
src/parse/recognizer.ts
test/parse/grammar/lookahead_spec.ts
test/parse/recognizer_lookahead_spec.ts

Implicit lookahead, can be distinguished using a single token lookahead.
This can only be checked during parser runtime
as the OR lookahead may be explicit or implict and this is
only known during parser runtime.

validation to check that the grammar in OR alternatives using

---

diagrams/src/diagrams_builder.js
src/api.ts
src/scan/tokens_public.ts
test/scan/token_spec.ts

Specifying `LABEL` on an ES6 class or add it to an ES5 contstructor customizes how a token is showed in documentation.
```
class Add extends Token {
static PATTERN = /\+/;
static LABEL = '+';
}
```
```
var Add = extendsToken('Add', '/\+/');
Add.LABEL = '+';
```

Human Readable Token Labels

---

CHANGELOG.md
src/parse/cache.ts
src/parse/parser_public.ts

in the context of a specific grammar.
This enables avoiding the rebuilding of the GAST representation
of an overriden rule on each and every initialization of the Parser.
Fixes #171

Cache information if a grammar production has already been overriden

---

CHANGELOG.md
examples/parser/predicate_lookahead/predicate_lookahead.js
src/parse/grammar/lookahead.ts
src/parse/parser_public.ts
test/full_flow/backtracking/backtracking_parser.ts
test/parse/predicate_spec.ts
test/parse/recognizer_lookahead_spec.ts
test/parse/recognizer_spec.ts

only add additional constraints to it.
Removed Parser.prototype.isNextRule method.
It is no longer needed the users of the library should never compute
lookahead funcitons. only predicates and backtracking.
Fixes #189.

Predicates / Gates of optional productions should not replace the basic grammar lookahead

---

performance/index.html

The littlest of nits, but it might save someone a little confusion.

Fix performance-test chart label typo

---

CHANGELOG.md
benchmark/parsers/cssDevParser.js
benchmark/parsers/cssOldParser.js
examples/grammars/css/css.js
src/parse/grammar/interpreter.ts
src/parse/grammar/lookahead.ts
src/parse/parser_public.ts
test/parse/grammar/interperter_spec.ts
test/parse/grammar/lookahead_spec.ts
test/parse/recognizer_lookahead_spec.ts

instead of DFS.
This avoids performance issues with the initialization of some parsers
As alot of unnecessary work was done which was determined by the configured maxLookahead
instead of the actual lookahead required for the specific grammar.
Thanks to @Levin81 for algorithmic assistance.
Fixes #243

BFS Style algorithim to compute the required Token lookahead 

---

CHANGELOG.md
examples/parser/parametrized_rules/parametrized.js
examples/parser/predicate_lookahead/predicate_lookahead.js
src/parse/gast_builder.ts
src/parse/grammar/lookahead.ts
src/parse/parser_public.ts
test/full_flow/backtracking/backtracking_parser.ts
test/parse/gast_builder_spec.ts
test/parse/predicate_spec.ts

Both The variant with Gates and Without Gates
Will use the "ALT" property for the grammar action.
The "GATE" property now replaces the "WHEN" property as it
more explicitly specifies the intent.
Fixes #192

Consistent API for "OR" DSL method.

---

benchmark/benchmark.js
src/parse/grammar/lookahead.ts
src/parse/parser_public.ts
src/utils/utils.ts
test/parse/recognizer_spec.ts

* Optimized lookahead functions for common case of K == 1.
* Partial Workaround lack of optimizations for TRY/CATCH in V8.
* Use NOOP functions for optional features, these NOOP functions
should be inlined by an optimizing compiler thus effectively
not existing...
* Other micro optimizations.
Performance Gains depend on the complexity of the grammar and the relationship
between lexing and parsing time in each specific use case (grammar).
For complex grammars as much as 12% boost has been benchmarked.

Performance Optimizations for 0.14.0 release.

---

benchmark/parsers/devJsonParser.js
benchmark/parsers/oldJsonParser.js
src/lang/lang_extensions.ts
src/parse/cache.ts
src/parse/parser_public.ts
test/parse/cache_spec.ts

The cached Keys are for cached lookahead functions.
This is slightly faster (1-4% on V8) than using
Short string keys, and in addition simplifies the key building logic
as a previous optimization to avoid string concat has now been removed.

Performance optimization: Create cache keys using bitwise operations.

---

benchmark/benchmark.js
benchmark/parsers/cssDevParser.js
benchmark/parsers/cssOldParser.js
benchmark/parsers/devJsonParser.js
benchmark/parsers/oldJsonParser.js
src/parse/grammar/lookahead.ts
src/parse/parser_public.ts
src/scan/lexer_public.ts
src/scan/tokens.ts
src/utils/utils.ts
test/parse/grammar/lookahead_spec.ts

Faster lookahead functions for common use case of no Token inheritance
and single token lookahead.
Improves Performance up to 10% in more complex grammars (On V8).

Performance Improvements: Lookahead functions

---

gruntfile.js
karma_sauce.conf.js

It should only update for results from the master branch.
This seems to require disabling SauceLabs browser testing on pull requests builds.
Because I was unable to get the "tags" feature of the karma saucelabs launcher to work.

Devops: Disable SauceLab badge always updating.

---

performance/index.html
performance/jsonParsers/browser/browser_json_parser.js
performance/jsonParsers/jsonify/jsonify_json_parser.js
performance/jsonParsers/oboe/oboe_json_parser.js
performance/lib/jsonify/jsonify.js

This adds on to the other PR as a base.
The existence of this new content is hidden unless there is a query param: `?jsons=true`
When that exists it:
1. adds a list describing the JSON specific parsers after the list of parser generator/combinators
2. adds the three to the table of parsers; excluded by default

Add json only

---

performance/index.html
performance/style.css

This took some work to figure out.
What happens now: as each library's benchmark is finished a sort happens so it will move to its new place in the list. The items are in the estimated order already, so, a lot of the time the results will show and no sorting animation will occur. Unless you don't include some tests. Then the ones included will move above the ones which aren't.
Also, I had the hand built parsers in their right order in relation to the others and they just appeared when the query param existed. That didn't work with the animation stuff because it places each element based on its position in the parent container. So, there were blank spaces where the hiding hand built ones were. So, I moved them to the end instead. When the user checks their "include" checkbox then they'll …

add animated sorting of results as each benchmark completes

---

examples/grammars/calculator/calculator.js
examples/grammars/json/json.js
examples/grammars/json/json_es6.js
examples/grammars/xml/xml_es6.js
examples/language_services/gruntfile.js
examples/lexer/multi_mode_lexer/multi_mode_lexer.js
examples/parser/content_assist/experimental_content_assist_in_parser_flow.js
examples/parser/content_assist/official_feature_content_assist.js
examples/parser/inheritance/inheritance.js
examples/parser/multi_start_rules/multi_start_rules.js
examples/parser/predicate_lookahead/predicate_lookahead.js
examples/parser/predicate_lookahead/predicate_lookahead_spec.js
examples/parser/versioning/versioning.js
src/parse/parser_public.ts

instead of
this.Statement = this.RULE("Statement", () => {...} )
Just
this.RULE("Statement", () => {...})
This change is backward compatiable, the old syntax still works...
This simpliy makes it so that the RULE method also creates a property on the "this"
and assigns the rule implemntation to that property.

Less verbose and error prone syntax to define Grammar rules.

---

examples/implementation_languages/coffeescript/coffeescript_json.coffee

A few changes:
1. when using `@` for `this.` the dot isn't needed
2. regular strings use single quotes, string interpolation uses double quotes
3. fat arrow isn't needed on these, and, because it does `bind()` for extra work, it's preferable to use regular arrows
4. instead of passing an empty array to build the instance, make that the default input param's value

Tweak coffeescript example

---

examples/grammars/calculator/calculator.js
examples/grammars/css/css.js
examples/grammars/json/json.js
examples/grammars/xml/xml_es6.js
examples/implementation_languages/ecma5/ecma5_json.js
examples/lexer/keywords_vs_identifiers/keywords_vs_identifiers.js
examples/lexer/multi_mode_lexer/multi_mode_lexer.js
examples/lexer/token_groups/token_groups.js
examples/lexer/token_types/token_types.js
examples/parser/content_assist/experimental_content_assist_in_parser_flow.js
examples/parser/content_assist/official_feature_content_assist.js
examples/parser/dynamic_tokens/dynamic_delimiters.js
examples/parser/inheritance/inheritance.js
examples/parser/minification/unminified.js
examples/parser/multi_start_rules/multi_start_rules.js
examples/parser/parametrized_rules/parametrized.js
examples/parser/predicate_lookahead/predicate_lookahead.js
examples/parser/versioning/versioning.js
src/api.ts
src/scan/lexer.ts
src/scan/lexer_public.ts
src/scan/tokens_public.ts
test/scan/lexer_spec.ts
test/scan/token_spec.ts
test/utils/matchers.ts
test_integration/sanity/json_parser_spec.js

The old extendToken utilities have been deprecated
as their API did not allow to support multiple optional arguments easily.
fixes #156
fixes #329

New createToken utility methods.

---

src/scan/lexer_public.ts
test/scan/lexer_spec.ts

The lexer logic currently does not properly handle tokens that define both `PUSH_MODE` and `POP_MODE` properties.  It will correctly pop the current lexer mode, but this updates `patternIdxToPushMode` to be the mapping of pattern indexes to push modes for the mode after the pop occurs.  Thus, when `patternIdxToPushMode` is checked to see if a mode needs to be pushed after the pop, it will likely check a token from the new mode that was never matched, instead of the original token.
This doesn't just affect tokens with both `PUSH_MODE` and `POP_MODE` properties, but can also cause modes to incorrectly be pushed when a token with a `PUSH_MODE` property occupies the same index as a token with a `POP_MODE` property in another mode.  For example, take the lexer defined in the tests, but …

Fix issue with tokens that both pop and push a mode

---

docs/tutorial/step4_fault_tolerance.md

Looks like I found another mistake. 😄

Fix documentation error for `recoveryEnabled`

---

docs/tutorial/step2_parsing.md

Looks like `parseErrors` is actually `undefined` in the current version.

Fix error detection example

---

src/parse/grammar/checks.ts
src/parse/grammar/lookahead.ts
src/parse/parser_public.ts
test/parse/grammar/checks_spec.ts
test/parse/grammar/lookahead_spec.ts

This PR adds a test to check if there are empty lookaheads, and makes chevrotain throw an error if there are.
There is currently some thoughts about tackling this the other way around and instead check if there are non-empty productions in repetitions, and throw an error if there are none. (See #401)

Add implementation for "no non-empty lookahead" test (Fixes #401)

---

CHANGELOG.md
package.json
src/parse/parser_public.ts
yarn.lock

TypeScript compiler option.
Fixes #459

Ensure chevrotain.d.ts is compatiable with noImplicitAny.

---

.idea/misc.xml
CHANGELOG.md
examples/language_services/tslint.json
src/parse/grammar/interpreter.ts
test/parse/grammar/interperter_spec.ts

* Lookahead calculation does not take into account the separator in X_SEP
DSL Methods.
* Possible Incorrect lookahead calculation in case of optional productions.
Fixes #391.

Lookahead Bug Fixs:

---

docs/tutorial/step1_lexing.md

In working through the tutorial it looks like there no `lexer` property of `chevrotain` just `Lexer`

Fixing some capitalization

---

examples/parser/webpack/package.json
package-lock.json
src/parse/errors_public.ts
src/parse/exceptions_public.ts
src/parse/parser_public.ts
test/parse/exceptions_spec.ts

also added the previous token to buildEarlyExitMessage

previousToken information for EarlyExitException (https://github.com/SAP/chevrotain#613)

---

examples/parser/custom_errors/custom_errors.js
src/api.ts
src/parse/cst/cst.ts
src/parse/errors_public.ts
src/parse/grammar/checks.ts
src/parse/grammar/gast/gast_resolver_public.ts
src/parse/grammar/resolver.ts
src/parse/parser_public.ts
test/parse/grammar/checks_spec.ts
test/parse/grammar/resolver_spec.ts

This is needed to enable support for custom APIs to create grammars.
I.E code generators or combinator using Chevrotain as the parsing runtime.
Part of #450

Support Custom Error Message for grammar analysis phase.

---

BREAKING_CHANGES.md
CHANGELOG.md
benchmark_web/parsers/css/css_dev.html
benchmark_web/parsers/css/css_latest.html
benchmark_web/parsers/ecma5/ecma5_dev.html
benchmark_web/parsers/ecma5/ecma5_latest.html
benchmark_web/parsers/json/json_dev.html
benchmark_web/parsers/json/json_latest.html
benchmark_web/parsers/options.js
docs/01_Tutorial/step2_parsing.md
docs/01_Tutorial/step3a_adding_actions_visitor.md
docs/02_Deep_Dive/concrete_syntax_tree.md
examples/grammars/calculator/calculator_pure_grammar.js
examples/grammars/ecma5/ecma5_parser.js
examples/parser/backtracking/backtracking_spec.js
examples/parser/parametrized_rules/parametrized.js
examples/tutorial/step1_lexing/step1_lexing.js
examples/tutorial/step2_parsing/step2_parsing.js
examples/tutorial/step3_actions/step3_actions_spec.js
examples/tutorial/step3_actions/step3a_actions_visitor.js
examples/tutorial/step3_actions/step3b_actions_embedded.js
src/parse/cache.ts
src/parse/cst/cst.ts
src/parse/parser_public.ts
test/parse/cst_spec.ts
test/parse/recognizer_spec.ts

- Avoids the creation of empty arrays in the "children"
object if no Terminal or NoneTerminal were matched.
- Avoids using "new Function" in CST flows to avoid issues with sites
using Content Security Policy.

CST upgrades for v3.0

---

gruntfile.js

folder structure in dev workspace.

unlink are integration tests to avoid cyclic

---

api.d.ts
yarn.lock

Minimal change to resolve issue #734. Adding null to other return types in `api.d.ts` does not really seem to be necessary for supporting strict compilation mode in client code. If I come across further issues while porting my code to typescript, I will create another pull request.

fixes #734 CustomPatternMatcherFunc return type now allows null value

---

examples/parser/package.json
examples/parser/serialized_grammar/README.md
examples/parser/serialized_grammar/gen/grammar.json
examples/parser/serialized_grammar/gen_serialized.js
examples/parser/serialized_grammar/grammar.js
examples/parser/serialized_grammar/serialized_spec.js
examples/parser/webpack/README.md

This is the work so far but it’s failing examples/parser tests for two reasons:
1. the tests use a shared cache and are (probably?) run in parallel, so clearing the cache in one test will cause other tests to fail.
2. the tests use the npm release of chevrotain and I can’t link my local package b/c the test command itself calls yarn.
I’ll pick it up again later, I just ran out of time for now.

Update docs for minifying chevrotain parsers with a serialized grammar

---

package.json

That typo makes some automatic tools (like `license-checker`) to incorrectly understand the license.

Typo in license name

---

packages/chevrotain/src/scan/reg_exp.ts
packages/chevrotain/test/scan/regexp_spec.ts

This fixes issues where the chevrotain Lexer engine fails to match tokens that _should_ match. The issues occur when tokens' RegExp patterns have nested capturing groups.
Test that failed before this PR and that pass afterward are included.
Closes #933.

Get correct startCodes for RegExp patterns with nested groups

---

packages/chevrotain/docs/features/backtracking.md

Fixing code example as using `BACKTRACK` in `GATE` does not require wrapping in function

Fix code example in backtracking docs

---

packages/chevrotain/benchmark_web/index.html
packages/chevrotain/src/parse/parser/traits/recognizer_engine.ts
packages/chevrotain/src/scan/lexer.ts
packages/chevrotain/src/scan/lexer_public.ts
packages/chevrotain/src/scan/reg_exp.ts
packages/chevrotain/src/scan/reg_exp_parser.ts
packages/chevrotain/test/scan/lexer_spec.ts
packages/chevrotain/test/scan/regexp_spec.ts

- Only Parse RegExp Sources once.
- Use "buckets" in first char optimiztions to avoid potentially creating many many small arrays.

Optimize Lexer Startup time.

---

packages/chevrotain/api.d.ts

Fixes #1014. I didn't see the need to create a separate type alias for this, but if you prefer that I'd be happy to change it.

Change CustomPatternMatcherFunc definition to match reality

---

packages/chevrotain/api.d.ts
packages/chevrotain/src/utils/utils.ts

The configuration's `pattern` property is directly assigned to a new `TokenType`'s `PATTERN` property, so their typing should be equal as well:
https://github.com/SAP/chevrotain/blob/86fec3e1f47aed1683e9005f94803f37b8086e30/packages/chevrotain/src/scan/tokens_public.ts#L63-L65

Make the type of TokenType.PATTERN equal to ITokenConfig.pattern

---

packages/chevrotain/docs/tutorial/step1_lexing.md

As discussed in #1027.
I'm not *completely* satisfied with this text, but it serves its purpose I think.

Add references to lexer modes and custom token patterns to the lexer tutorial

---

packages/chevrotain/api.d.ts
packages/chevrotain/docs/.vuepress/config.js
packages/chevrotain/docs/changes/BREAKING_CHANGES.md
packages/chevrotain/docs/guide/resolving_grammar_errors.md
packages/chevrotain/src/parse/grammar/checks.ts
packages/chevrotain/src/parse/grammar/gast/gast_resolver_public.ts
packages/chevrotain/src/parse/parser/parser.ts
packages/chevrotain/test/parse/grammar/checks_spec.ts
packages/chevrotain/test/parse/recognizer/recognizer_config_spec.ts
packages/chevrotain/test/parse/recognizer_lookahead_spec.ts

Docs included in commit
BREAKING CHANGE: The `ignoredIssues` property was removed and a Parser will throw an error if said
property is used.

feat: hard Deprecate `ignoredIssues` IParserConfig property

---

packages/chevrotain/src/scan/lexer.ts
packages/chevrotain/test/scan/lexer_spec.ts

This PR fixes issue #1141 - create single character token pattern with ignore flag
It only affects the lexer
A test is included

fix(lexer): Literal single token character "ignore case" flag bug

---

examples/custom_apis/combinator/combinator_api.js
packages/chevrotain/api.d.ts
packages/chevrotain/docs/changes/BREAKING_CHANGES.md
packages/chevrotain/docs/guide/custom_apis.md
packages/chevrotain/src/api.ts
packages/chevrotain/src/generate/generate.ts
packages/chevrotain/src/parse/grammar/checks.ts
packages/chevrotain/src/parse/grammar/follow.ts
packages/chevrotain/src/parse/grammar/gast/gast.ts
packages/chevrotain/src/parse/grammar/gast/gast_public.ts
packages/chevrotain/src/parse/grammar/gast/gast_visitor_public.ts
packages/chevrotain/src/parse/grammar/interpreter.ts
packages/chevrotain/src/parse/grammar/lookahead.ts
packages/chevrotain/src/parse/grammar/rest.ts
packages/chevrotain/src/parse/parser/traits/gast_recorder.ts
packages/chevrotain/test/generate/generate_spec.ts
packages/chevrotain/test/parse/grammar/checks_spec.ts
packages/chevrotain/test/parse/grammar/first_spec.ts
packages/chevrotain/test/parse/grammar/gast_spec.ts
packages/chevrotain/test/parse/grammar/interperter_spec.ts
packages/chevrotain/test/parse/grammar/lookahead_spec.ts
packages/chevrotain/test/parse/grammar/resolver_spec.ts
packages/chevrotain/test/parse/grammar/samples.ts

the name Flat was not accurate enough...
BREAKING CHANGE: rename Flat to Alternative in GAST structure, this is part of the public API

refactor: rename Flat -> Alternative in GAST structure

---

examples/lexer/python_indentation/python_indentation.js
examples/lexer/python_indentation/python_indentation_spec.js

The python indentation example had a problem with more than one line at the same indent level.
e.g:
const {tokens} = tokenize(`
if
1
2
`)
console.log(tokens.map(t => [t.image, t.tokenType.name]))
Would output:
[ 'If', 'Indent', 'IntegerLiteral', 'Outdent', 'IntegerLiteral' ]
The outdent comes before the '2' instead of after.
Improved test case and fix in this PR.

Fix issue with python indentation example

---

packages/chevrotain/src/parse/cst/cst_visitor.ts
packages/chevrotain/src/parse/grammar/checks.ts
packages/chevrotain/test/parse/grammar/checks_spec.ts

Added the possibility to use the dash character in the middle of a token name.
This requirement comes from an idea of the ASN1 language compilation.
ASN1 has keywords like :
ENCODING-CONTROL
RELATIVE-OID-IRI'
ABSTRACT-SYNTAX
TYPE-IDENTIFIER
MINUS-INFINITY
PLUS-INFINITY
NOT-A-NUMBER
RELATIVE-OID
TIME-OF-DAY
DATE-TIME
OID-IRI

feat: allow dash (-) in token name (#1291)

---

packages/chevrotain/src/parse/parser/traits/tree_builder.ts

I'd like to define the types of ICSTVisitor rather than having it always be of type `any`.

Add generics to getBaseCSTVisitorConstructor

---

packages/chevrotain/api.d.ts

Following discussion in #1305 I made a minimal patch to the type declarations.

fix: update type declaration for CstChildrenDictionary

---

packages/chevrotain/api.d.ts
packages/chevrotain/package.json
packages/chevrotain/scripts/fix-coverage-report.js
packages/chevrotain/src/parse/exceptions_public.ts
packages/chevrotain/test/parse/exceptions_spec.ts
packages/chevrotain/test_integration/definitions/api_type_checking.ts
yarn.lock

Fixes #1316
Also converts error constructors to classes to satisfy typing in the api_type_checking.ts test.
Note: should be able to remove the ES5 downlevel workarounds when the TS target is updated to a more modern runtime.  Since babel@7 seems to be able to downlevel custom class errors to behave like ES2015 (i.e. with prototype and stacktrace intact).

fix: add missing members to parser exception type declarations

---

packages/chevrotain/package.json

There has been a rename from `api.d.ts` to `chevrotain.d.ts`

fix: update packaged files

---

packages/utils/package.json

Build currently works because it implicitly converts them to `any`.
Might be worth enabling `noImplicitAny` or `strict` in `tsconfig.json` to capture these cases in the future.  Might be a bit of work though.  ~500 errors when I enabled `noImplicitAny` locally.

fix: update typings path for @chevrotain/utils

---

packages/chevrotain/package.json
yarn.lock

I'm pretty sure `gen-esm-wrapper` should automatically exclude `__esModule` but at least it gives us a way to do it without updating the library.
Fixes #1537

Exclude __esModule from esm wrapper 

---

packages/types/api.d.ts

This change was done b/c the angle brackets break the compiler for [typedoc-plugin-markdown](https://github.com/tgreyuk/typedoc-plugin-markdown), a library for converting Typedoc to markdown. It interprets the angle brackets as an HTML tag, whereas it's just being used for emphasis.
This issue occurred specifically when using [docusaurus-plugin-typedoc](https://www.npmjs.com/package/docusaurus-plugin-typedoc). More details about this problem can be found here - https://github.com/tgreyuk/typedoc-plugin-markdown/issues/276
This change fixes the issues by replacing the backticks (`<` and `>`) with markdown backticks to highlight the word and achieve the same desired emphasis without breaking the markdown parser.
i was able to validate that this works in my local environment.

docs: change angle brackets to backticks in comment

---

README.md

Fixes a silly syntax mistake I made in my previous pull request (#1763), where I set out to fix a little mistake introduced in the commit f03468fe13b5bca56ea7abaf83f000033760ef94. I've tested my changes this time, sorry!

Fix syntax of Markdown links in README.md

---

packages/types/api.d.ts

this is necessary as they aren't all 0 or 1 indexed
(cherry picked from commit 0aa07e5ae10d5420ec03c37b9e4978f5d8caf94e)

additional description on token location attributes

---

examples/grammars/ecma5/ecma5_parser.js
packages/chevrotain/benchmark_web/parsers/ecma5/ecma5_parser.js
packages/chevrotain/src/parse/grammar/atn.ts
packages/chevrotain/src/parse/grammar/atn_simulator.ts
packages/chevrotain/src/parse/grammar/dfa.ts
packages/chevrotain/src/parse/grammar/lookahead.ts
packages/chevrotain/src/parse/parser/traits/looksahead.ts
packages/chevrotain/test/parse/grammar/atn_spec.ts

Does three things:
1. Adds syntactic predicates to the ECMA5 parsers to correctly work with ambiguities and LL(*)
2. Fixes backtracking tests by adding a stricter heuristic for ambiguities
3. Changes the order of predicate evaluation. Instead of evaluating them at the end like Antlr does, we evaluate them at the start and create a distinct DFA for each configuration of predicates.

LL(*): Fix ECMA5 prediction and backtracking tests

---

packages/types/api.d.ts

Generics were added to getBaseCstVisitorConstructor() and getBaseCstVisitorConstructorWithDefaults()
in PR #1303. However, the typescript definitions were not updated.

fix(api.d.ts): updated typescript definitions for getBaseCstVisitorConstructor functions.

---

playground/examples.js

See https://github.com/Chevrotain/chevrotain/blob/master/packages/chevrotain/benchmark_web/parsers/json/json_parser.js
":?" is an optional :, not a non-capturing group. Additionally, nested + and * lead to terrible performance when not matching.
Fixes #1788

copy StringLiteral from benchmark parser

---

packages/utils/src/to-fast-properties.ts

I tested it with the benchmark_web/index_next.html in Firefox and it seems to work.
Fixes #1787

fix: suppress Firefox warning of unreachable code

---

packages/types/api.d.ts

Hi,
just a small link fix from the `api.d.ts` file I stumbled upon.
Thanks for developing and maintaining your awesome parser!
re #1751

docs: fixed link to "CstNodes Location" (missing s) and changed protocol to https

---

packages/chevrotain/src/scan/lexer_public.ts
packages/chevrotain/test/scan/lexer_spec.ts
packages/types/api.d.ts

Setting recoveryEnabled to false on an instance of the Lexer class will prevent chevrotain from
trying to consume more characters when it cannot match a token at the current scanning offset
fix #1838
Useful when a token does not match but may match on the next character. For instance I match 'account names' which can optionally be surrounded by parentheses, but can also contain parentheses if not fully surrounded. ex:
'Real' accounts
```
Assets:Chequing
Assets:Joint Chequing
(An)Asset:Chequing
```
'Virtual' accounts
```
(Assets:Chequing)
(Assets:Joint Chequing
((An)Asset:Chequing)
```
Due to the interspersed brackets, it isn't easy to take care of the () in the parser as separate tokens, as I'd have to concatenate the internal parentheses and text segments. In some places I want to ONLY …

feat(lexer): added recoveryEnabled option to the Lexer class configuration

---

packages/chevrotain/src/parse/cst/cst_visitor.ts
packages/chevrotain/test/parse/cst_visitor_spec.ts
packages/types/api.d.ts
tsconfig.json

This validation was problematic because different
manners of inheritance implementations in js may require
different approaches for enumerating the method names
Additionally this validation did not handle the case of custom
utilities on visitors which resulted in false positives.

chore: remove validation for redundant methods

---

packages/types/api.d.ts

`IRecognitionException` doesn't  extend `Error`, so for example
```typescript
parserInstance.errors[0].stack
```
is not recognized by typescript.

docs: IRecognitionException should extend 'Error'

---

packages/chevrotain/src/parse/grammar/llk_lookahead.ts
packages/chevrotain/src/parse/parser/parser.ts
packages/types/api.d.ts

1. Fixes the missing call to the lookahead initialization method
2. Adds the `{ maxLookahead: number }` options to the LLk constructor

fix: missing call to lookahead initialization

---

packages/chevrotain/package.json

ESM only packages fails to find the types.
A copy of type file is required to make `tsc` succeed:
https://github.com/jhipster/generator-jhipster/blob/main/jdl/chevrotain.d.ts
Reference for package.json exports field:
https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing
```
"exports": {
".": {
// Entry-point for TypeScript resolution - must occur first!
"types": "./types/index.d.ts",
// Entry-point for `import "my-package"` in ESM
"import": "./esm/index.js",
// Entry-point for `require("my-package") in CJS
"require": "./commonjs/index.cjs",
},
},
```

chore: add types at package.json exports

---

packages/cst-dts-gen/package.json
packages/gast/package.json
packages/utils/package.json

Modern bundler settings require the exports field to be present. See https://github.com/Chevrotain/chevrotain/issues/1941

fix: add missing exports field

---

packages/regexp-to-ast/.mocharc.js
packages/regexp-to-ast/nyc.config.js
packages/regexp-to-ast/package.json
packages/regexp-to-ast/src/regexp-to-ast.js
packages/regexp-to-ast/test/parser.spec.js
packages/regexp-to-ast/test/visitor.spec.js
pnpm-lock.yaml

As requested as part of this [PR](https://github.com/bd82/regexp-to-ast/pull/129), I started to work on bringing regexp-to-ast to inside of the chevrotain mono repo.
Test is passing, I still need to figure out how to release.

feat: add regexp-to-ast package

---

examples/lexer/keywords_vs_identifiers/keywords_vs_identifiers.js

Fix typos and punctuation, and improve some wordings a little.
Some of these changes might be objected.  I'm open to suggestions.  ^^

docs: fix typos, punctuation in keywords_vs_identifiers.js

---

packages/website/docs/tutorial/step1_lexing.md

Someone must've hit `"` by accident, which is right next to `:` on the ANSI keyboard layout.

docs: fix punctuation in step1_lexing.md

---

tsconfig.base.json

- Reduces `chevrotain.min.js` by ~30Kb (#1697)
- Was already introduced in 10.x version but reverted in 10.3.0 due to unexpected breaking changes.
- see: https://github.com/Chevrotain/chevrotain/issues/1845#issuecomment-1221411613

build!: change compile target to ES2015

---

packages/types/api.d.ts

Because `api.d.ts` incorrectly defines `input` as a data property instead of an [accessor property (as it's defined in code)](https://github.com/Chevrotain/chevrotain/blob/master/packages/chevrotain/src/parse/parser/traits/lexer_adapter.ts#L23-L40), then TypeScript will throw compilation errors if you try to override the parser's input accessor.
If you attempt to augment the Chevrotain types (with `declare module 'chevrotain'` and altering the interface), TypeScript will still fail, because the name exists, it's just incorrectly defined. The only workaround is to add a `@ts-ignore`. (Even `@ts-expect-error` will cause problems, because extensions like Volar cannot correctly determine that `tsc` will error in this case.)

Update api.d.ts to properly define `input`

---

performance/index.html

As of 2024-03-16, https://pegjs.org no longer hosts content related to the PEG.js project -- see https://web.archive.org/web/20240316193229/https://pegjs.org/
* https://github.com/pegjs/pegjs/issues/639
* https://github.com/pegjs/pegjs/issues/675

Discourage people from considering PEG.js

---

examples/lexer/custom_errors/custom_errors.js
packages/chevrotain/src/scan/lexer_errors_public.ts
packages/chevrotain/src/scan/lexer_public.ts
packages/chevrotain/test/scan/lexer_errors_public_spec.ts
packages/chevrotain/test/scan/lexer_spec.ts
packages/types/api.d.ts

As discussed in #2078 
Note: even though the mode will always be provided, I declared it as `mode?: string` to avoid breaking changes.
Other options would include
- putting the mode parameter before the optional line and column parameters
- changing the declaration of line and column from `line?: number` to `line: number | undefined`
Both of these would be breaking changes. If you prefer any of these options, just let me know

feat: add current lexer mode to buildUnexpectedCharactersMessage
