- examples/backtracking/BackTrackingParser.ts
- examples/errorRecovery/sqlStatements/SqlRecoveryParser.ts
- examples/errorRecovery/sqlStatements/SqlRecoverySpec.ts
- src/parse/GAstBuilder.ts
- src/parse/Recognizer.ts
- src/parse/grammar/GAst.ts
- src/parse/grammar/Interpreter2.ts
- src/parse/grammar/Lookahead.ts
- src/parse/grammar/Path.ts
- test/parse/RecognizerLookAheadSpec.ts
- test/parse/grammar/InterperterSpec.ts
- test/parse/grammar/LookaheadSpec.ts
- test/parse/grammar/Samples.ts
this breaks some functionality related to inRepetition recovery.
however this will be fixed in a different commit.
> automatic lookahead calculation for MANY dsl RULE.

- examples/errorRecovery/sqlStatements/SqlRecoveryParser.ts
- examples/errorRecovery/switchCase/SwitchCaseRecoveryParser.ts
- examples/jsonParserOnly/JsonParser2.ts
- src/parse/GAstBuilder.ts
- src/parse/Recognizer.ts
- src/parse/grammar/Follow.ts
- src/parse/grammar/Interpreter2.ts
- src/parse/grammar/Lookahead.ts
- src/parse/grammar/Path.ts
- src/parse/grammar/Rest.ts
- test/parse/RecognizerSpec.ts
- test/parse/grammar/InterperterSpec.ts
This only done implicitly without any ability
to provide the params explicitly.
> automatic calculation of params for In Repetion recovery.

- bower.json
- gruntfile.js
also added a check to avoid this mismatch happening again.
> sync npm and bower lodash dep version.

- examples/ecmascript5/ecmascript5_parser.ts
also includes some minor fixes.
> Function/Program part of the ECMAScript5 spec.

- examples/ecmascript5/ecmascript5_lexer_spec.ts
- examples/ecmascript5/ecmascript5_parser.ts
- examples/ecmascript5/ecmascript5_parser_spec.ts
- examples/ecmascript5/ecmascript5_tokens.ts
- examples/ecmascript5/ecmascript5_zlexer.ts
this is still missing a few things which will be handled in future
commits.
1. RegExp literal
2. error tolerance
3. error messages
> Inital EcmaScript5 Lexer example based on Esprima's implementation.

- build/chevrotain.ts
- examples/ecmascript5/ecmascript5_parser.ts
- examples/error_recovery/sql_statements/sql_recovery_parser.ts
- src/parse/gast_builder.ts
- src/parse/grammar/checks.ts
- src/parse/recognizer.ts
- test/parse/grammar/validations_spec.ts
- test/parse/recognizer_lookahead_spec.ts
- test/parse/recognizer_spec.ts
* The validation is done once only when the first instance is instanciated
* The validation will throw an error in case there is one in order to stop
the developer from working if he has errors
* CONSUME with the same token as a parameter cannot appear more than once
with the same occurence number in the same top rule
* SUBRULE with the same production reference and the same occurrence number
cannot appear more than once in the same top rule
* MANY, OR, OPTION, AT_LEAS_ONE cannot appear more than once with the same
occurrence number in the same top rule
> Occurrence number validation

- .travis.yml
- gruntfile.js
- karma.conf.js
- src/api.ts
- src/parse/cache.ts
- src/parse/cache_public.ts
- test/parse/cache_spec.ts
fixes #127.
Due to random instability of browser tests on Travis-CI
* Split up browsers tests
* use concurrency = 1 in karma.config
> * Expose ClearCache functionality in the external API.

- bower.json
- diagrams/diagrams.css
- diagrams/diagrams.html
- diagrams/readme.md
- diagrams/sample/DUMMY_SAMPLE.js
- diagrams/src/diagrams_behavior.js
- diagrams/src/diagrams_builder.js
- diagrams/src/main.js
- diagrams/vendor/railroad-diagrams.js
- examples/typescript_ecma5/.gitignore
- examples/typescript_ecma5/README.md
- examples/typescript_ecma5/ecma5_diagrams.html
- package.json
See included diagrams/readme.md for details.
fixes #138
> A template html to generate diagrams for grammars.

- diagrams/src/diagrams_builder.js
- diagrams/src/main.js
Fixes the diagram builder to load chevrotain via UMD when available
> Fixed global references to permit UMD loading

- CHANGELOG.md
- examples/lexer/README.md
- examples/lexer/keywords_vs_identifiers.js
- examples/lexer/multi_mode_lexer.js
- examples/lexer/multi_mode_lexer_spec.js
- examples/lexer/package.json
- examples/lexer/token_groups.js
- src/scan/lexer.ts
- src/scan/lexer_public.ts
- src/utils/utils.ts
- test/scan/lexer_spec.ts
- test/utils/utils_spec.ts
> Lexer modes Support.

- CHANGELOG.md
- examples/parser/versioning/versioning.js
- examples/parser/versioning/versioning_spec.js
- src/parse/grammar/checks.ts
- src/parse/parser_public.ts
- test/parse/grammar/checks_spec.ts
- test/parse/recognizer/rules_override_spec.ts
- test/parse/recognizer_spec.ts
> Support Overriding Rule implementations in inheriting grammars.

- CHANGELOG.md
- docs/tutorial/step4_fault_tolerance.md
- src/parse/parser_public.ts
- test/full_flow/backtracking/backtracking_parser.ts
- test/full_flow/error_recovery/sql_statements/sql_recovery_parser.ts
- test/full_flow/error_recovery/switch_case/switchcase_recovery_parser.ts
- test/parse/recognizer/rules_override_spec.ts
- test/parse/recognizer_lookahead_spec.ts
- test/parse/recognizer_spec.ts
Remove RULE_NO_RESYNC DSL method.
Use a config object for RULE DSL method.
Fixes #168
Fixes #172
> Refactor RULE & RULE_NO_RESYNC methods APIs

- examples/parser/versioning/versioning.js
- src/parse/grammar/gast.ts
- src/parse/grammar/gast_public.ts
- src/parse/parser_public.ts
- test/parse/recognizer/rules_override_spec.ts
> Fix - GAST cache does not take into account grammar inheritance

- .idea/watcherTasks.xml
- CHANGELOG.md
- src/parse/grammar/lookahead.ts
- src/parse/parser_public.ts
- test/parse/grammar/lookahead_spec.ts
- test/parse/predicate_spec.ts
> Bug Fix: Predicates and Rule Parameters combination.

- CHANGELOG.md
- examples/parser/package.json
- examples/parser/parametrized_rules/parametrized.js
- examples/parser/parametrized_rules/parametrized_spec.js
- gruntfile.js
- readme.md
> Example using parametrized sub-rules.

- diagrams/src/diagrams_behavior.js
- diagrams/vendor/railroad-diagrams.js
Fixes #229
ase enter the commit message for your changes. Lines starting
> Fix Syntax Diagrams highlights under IE Edge.

- CONTRIBUTING.md
- package.json
- readme.md
> Chore: Created a CONTRIBUTING.md

- docs/faq.md
- readme.md
> Chore: Creating faq.md

- .idea/inspectionProfiles/Project_Default.xml
- .idea/misc.xml
- performance/index_nearley.html
- performance/jsonParsers/nearley/api.js
- performance/jsonParsers/nearley/json_grammar.ne
- performance/jsonParsers/nearley/nearley_json_parser.js
- performance/jsonParsers/nearley/readme.md
- performance/samples/1K_json_no_escaping.js
and 1,000 lines input.
it is very slow, too slow to add to the benchmark with multiple Parsing solutions...
This is also not the complete JSON grammar.
Not whitespace handling (as it seems to slow nearley even more)
and without complete JSON string escapes as that too slows Nearley
way too much.
This is meant to reproduce the low performance with a minimal example.
Not added t
> Nearley performance benchmark using a JSON grammar

- docs/tutorial/step2_parsing.md
I just saw this mistake while reading the documentation and I thought I might as well fix it :)
> Fixed spelling

- benchmark/benchmark.js
- benchmark/parsers/devJsonParser.js
- benchmark/parsers/oldJsonParser.js
- benchmark/sampes/json10k.js
- examples/grammars/calculator/calculator.js
- examples/grammars/calculator/calculator_spec.js
- examples/grammars/css/css.js
- examples/grammars/css/css_spec.js
- examples/grammars/json/json.js
- examples/grammars/json/json_es6.js
- examples/grammars/xml/xml_es6.js
- examples/parser/dynamic_tokens/dynamic_delimiters.js
- examples/parser/dynamic_tokens/dynamic_delimiters_spec.js
- examples/parser/inheritance/inheritance.js
- examples/parser/minification/minify_spec.js
- examples/parser/minification/unminified.js
- examples/parser/multi_start_rules/multi_start_rules.js
- examples/parser/parametrized_rules/parametrized.js
- examples/parser/predicate_lookahead/predicate_lookahead.js
- examples/parser/predicate_lookahead/predicate_lookahead_spec.js
- examples/parser/versioning/versioning.js
- src/parse/parser_public.ts
- test_integration/sanity/json_parser_spec.js
Combination of performance improvements after some in depth profiling of Chevrotain running under V8.
fixes #248
> Performance improvements.

- benchmark/parsers/cssDevParser.js
- benchmark/parsers/cssOldParser.js
- benchmark/parsers/devJsonParser.js
- examples/parser/dynamic_tokens/dynamic_delimiters.js
- src/parse/grammar/lookahead.ts
- src/parse/parser_public.ts
- src/scan/tokens.ts
- src/scan/tokens_public.ts
- src/utils/utils.ts
- test/parse/grammar/lookahead_spec.ts
- test/scan/token_spec.ts
> "Smart" Map based lookahead for K = 1 with Token inheritance.

- CHANGELOG.md
- docs/token_types.md
- src/scan/lexer_public.ts
- src/scan/tokens.ts
- src/scan/tokens_public.ts
- test/parse/grammar/lookahead_spec.ts
- test/scan/token_spec.ts
> SimpleTokens to support Token Inheritance.

- .idea/.name
- src/scan/lexer.ts
- src/scan/lexer_public.ts
- test/scan/lexer_spec.ts
> Lexer Token Groups were not reset on each Tokenize call.

- src/parse/parser_public.ts
- test/parse/recognizer_spec.ts
> Faster failures for Parsers without error recovery enabled.

- performance/index.html
- performance/index_nearley.html
- performance/index_nearley_tokenizer.html
- performance/token_types/index.html
No generated code changes for Nearley.
> Updated library versions in performance runner

- performance/index.html
Okay, now that I'm about to post this, I reread your post and noticed the sorted and "include" stuff should be separate. Woops. I put them together. Please, feel free to change them to the previous order you had. Mostly, this PR makes these changes:
1. the table has a new column for checkboxes to control whether a test is included in the "Run"
2. the rows and cells have ID's on them to allow grabbing them directly for setting values into them
3. the Ohm test, which, you're right, is by far the slowest, is unchecked by default, but now is always shown.
> Sorted excludable

- examples/grammars/css/css.js
- examples/grammars/json/json.js
- examples/parser/dynamic_tokens/dynamic_delimiters.js
- examples/parser/minification/unminified.js
- examples/parser/parametrized_rules/parametrized.js
> Convert additional examples to using the new rule API.

- examples/README.md
- examples/implementation_languages/.gitignore
- examples/implementation_languages/README.md
- examples/implementation_languages/coffeescript/coffeescript_json.coffee
- examples/implementation_languages/ecma5/ecma5_json.js
- examples/implementation_languages/ecma6/ecma6_json.js
- examples/implementation_languages/impl_lang_spec.js
- examples/implementation_languages/package.json
- examples/implementation_languages/typescript/typescript_json.ts
- gruntfile.js
> Examples of using Chevrotain using different implementation Languages.

- docs/custom_token_patterns.md
- examples/lexer/README.md
- examples/lexer/custom_patterns/custom_patterns.js
- examples/lexer/custom_patterns/custom_patterns_spec.js
- readme.md
- src/scan/lexer.ts
- src/scan/lexer_public.ts
- src/scan/tokens_public.ts
- src/utils/utils.ts
- test/scan/lexer_spec.ts
> Support Lexing with custom(None RegExp) Token Patterns.

- examples/grammars/package.json
- examples/implementation_languages/ecma6/ecma6_json.js
- examples/implementation_languages/package.json
- examples/lexer/package.json
- examples/parser/README.md
- examples/parser/package.json
- examples/parser/webpack/.babelrc
- examples/parser/webpack/.gitignore
- examples/parser/webpack/README.md
- examples/parser/webpack/package.json
- examples/parser/webpack/src/grammar_only_commonjs_require.js
- examples/parser/webpack/src/grammar_only_es6_import.js
- examples/parser/webpack/src/tokens_and_grammar.js
- examples/parser/webpack/src/tokens_only.js
- examples/parser/webpack/test/webpack_spec.js
- examples/parser/webpack/webpack.config.js
- gruntfile.js
> Example & Docs for using Webpack 2 with Chevrotain.

- benchmark/parsers/cssDevParser.js
- src/scan/lexer.ts
- src/scan/lexer_public.ts
- test/scan/lexer_spec.ts
> Lexer performance improvements.

- examples/lexer/python_indentation/python_indentation.js
- examples/lexer/python_indentation/python_indentation_spec.js
> Adds multiple Outdent tokens support in python indentation example

- docs/custom_token_patterns.md
- examples/lexer/python_indentation/python_indentation.js
- src/scan/lexer.ts
- src/scan/lexer_public.ts
- src/scan/tokens_public.ts
- src/utils/utils.ts
- test/parse/gast_builder_spec.ts
- test/parse/grammar/checks_spec.ts
- test/parse/recognizer_lookahead_spec.ts
- test/scan/lexer_spec.ts
> Using sticky flag for lexer performance.

- docs/resolving_grammar_errors.md
- src/parse/grammar/checks.ts
- src/parse/grammar/lookahead.ts
- src/parse/parser_public.ts
- src/utils/utils.ts
- test/parse/grammar/checks_spec.ts
> Detection of alternations prefix ambiguities.

- docs/concrete_syntax_tree.md
- docs/tutorial/step1_lexing.md
- docs/tutorial/step2_parsing.md
- docs/tutorial/step3_adding_actions_root.md
- docs/tutorial/step3a_adding_actions_separated.md
- docs/tutorial/step3b_adding_actions_embedded.md
- docs/tutorial/step4_fault_tolerance.md
- examples/grammars/README.md
- examples/grammars/calculator/calculator_embedded_actions.js
- examples/grammars/calculator/calculator_pure_grammar.js
- examples/grammars/calculator/calculator_spec.js
- src/parse/cache.ts
- src/parse/cst/cst.ts
- src/parse/cst/cst_public.ts
- src/parse/cst/cst_visitor.ts
- src/parse/parser_public.ts
- test/parse/cst_visitor_spec.ts
> CST visitor

- docs/tutorial/readme.md
- docs/tutorial/src/.gitignore
- docs/tutorial/src/README.md
- docs/tutorial/src/package.json
- docs/tutorial/src/step1_lexing.js
- docs/tutorial/src/step2_parsing.js
- docs/tutorial/src/step3a_actions_visitor.js
- docs/tutorial/src/step3b_actions_embedded.js
- docs/tutorial/src/tutorial_spec.js
- docs/tutorial/step1_lexing.md
- docs/tutorial/step2_parsing.md
- docs/tutorial/step3a_adding_actions_visitor.md
- docs/tutorial/step3b_adding_actions_embedded.md
- gruntfile.js
> Offline tutorial.

- performance/README.md
- performance/index.html
- performance/jsonParsers/handbuilt/handbuilt.html
- performance/jsonParsers/handbuilt/handbuilt.js
- performance/style.css
> Hand Built Parser in perf benchmark.

- CHANGELOG.md
- docs/faq.md
- src/parse/parser_public.ts
- test/parse/recognizer/recognizer_config_spec.ts
> Smaller default maxLookahead.

- performance/jsonParsers/myna/myna.html
I have improved the performance significantly in 2.1.0. Ideally I would like to have this point to the latest version of Myna, so that I can make updates (like I just did) and have the performance benchmarks updated accordingly, without having to request a pull each time.
> Use latest version of Myna (2.1.0).

- .travis.yml
* Re-add cache.
* Use built in yarn.
> Travis upgrades.

- examples/parser/custom_errors/custom_errors.js
- examples/parser/custom_errors/custom_errors_spec.js
- gruntfile.js
- src/api.ts
- src/parse/errors_public.ts
- src/parse/parser_public.ts
- src/utils/utils.ts
- tslint.json
> Custom user errors support.

- gruntfile.js
- package.json
- webpack_release.config.js
- webpack_release_min.config.js
- webpack_specs.config.js
- yarn.lock
* Remove webpack grunt plugin.
> * Update webpack.

- benchmark_web/README.md
- benchmark_web/index.html
- benchmark_web/parsers/api.js
- benchmark_web/parsers/chevrotainParser.js
- benchmark_web/parsers/json_dev.html
- benchmark_web/parsers/json_latest.html
- benchmark_web/samples/1K_json.js
- benchmark_web/style.css
- package.json
Should be easier to run without hacks locally.
Still need to look into running each Chevrotain version in
its own web worker.
> New Browser based benchmark.

- gruntfile.js
- package.json
May grunt rest in peace.
Part of #509
> Remove grunt_typedoc plugin.

- benchmark_web/index.html
- benchmark_web/parsers/css/1K_css.js
- benchmark_web/parsers/css/css_dev.html
- benchmark_web/parsers/css/css_latest.html
- benchmark_web/parsers/css/css_parser.js
- benchmark_web/parsers/json/1K_json.js
- benchmark_web/parsers/json/json_dev.html
- benchmark_web/parsers/json/json_latest.html
- benchmark_web/parsers/json/json_parser.js
- benchmark_web/parsers/worker_api.js
- benchmark_web/parsers/worker_impel.js
- examples/grammars/css/css.js
- examples/grammars/css/css_diagrams.html
- gruntfile.js
> Use webworkers in bechmark for greater isolation.

- src/parse/parser_public.ts
- test/parse/recognizer_spec.ts
Causes a slight reductions in performance under V8 (1-2%).
Worth it to avoid the complexity...
Fixes #323
> Avoids try/catch optimizations.

- lexer_adapter.md
- src/parse/grammar/lookahead.ts
- src/parse/parser_public.ts
- test/full_flow/ecma_quirks/ecma_quirks.ts
- test/full_flow/ecma_quirks/ecma_quirks_spec.ts
- test/parse/grammar/lookahead_spec.ts
> Refactor and Example for LexerLess Parser (ECMAScript)

- docs/tutorial/step3a_adding_actions_visitor.md
> Fixed incorrect method name

- docs/tutorial/step3_adding_actions_root.md
> Fixed typo

- src/parse/grammar/checks.ts
- src/parse/parser_public.ts
- test/parse/grammar/checks_spec.ts
> Validation to check for too many alternatives.

- CHANGELOG.md
- src/scan/tokens_public.ts
> Missing docs link in deprecation check.

- src/parse/parser_public.ts
- test/full_flow/backtracking/backtracking_parser.ts
- test/full_flow/ecma_quirks/ecma_quirks.ts
- test/full_flow/error_recovery/switch_case/switchcase_recovery_parser.ts
- test/parse/grammar/interperter_spec.ts
- test/parse/predicate_spec.ts
- test/parse/recognizer_lookahead_spec.ts
- test/parse/recognizer_spec.ts
> Increase maximum suffixes for DSL methods.

- api.d.ts
- src/parse/errors_public.ts
- src/parse/exceptions_public.ts
- src/parse/parser_public.ts
- test/full_flow/ecma_quirks/ecma_quirks.ts
- test/parse/exceptions_spec.ts
adds previousToken info for NoViableAltException and MismatchedTokenException
> fixes #613 

- api.d.ts
- yarn.lock
> fixed groups parameter type in CustomPatternMatcherFunc

- api.d.ts
- src/parse/gast_builder.ts
- src/parse/grammar/gast/gast_public.ts
- src/parse/parser_public.ts
- test/parse/gast_builder_spec.ts
- test/parse/grammar/gast_spec.ts
- test/parse/recognizer_spec.ts
Implements steps 1 and 2 of #706
> Implement grammar AST de-serialization and allow passing of serialized grammar to performSelfAnalysis

- package.json
- src/scan/reg_exp.ts
- test/scan/regexp_spec.ts
- yarn.lock
> Update regexp-to-ast version.

- docs/changes/CHANGELOG.md
- src/parse/parser_public.ts
- test/parse/recognizer_spec.ts
> Fixes for OVERRIDE_RULE.

- docs/.vuepress/config.js
- docs/FAQ.md
> Fixed typo in FAQ

- src/parse/grammar/checks.ts
- test/parse/grammar/checks_spec.ts
> Fix stack overflow during gramamr analysis.

- .idea/codeStyles/Project.xml
- .travis.yml
> Attempt to reduce number of containers used in travis build.

- src/scan/lexer.ts
Current link is broken, made it same as for '$' anchor
> Fix broken link to docs

- packages/chevrotain/docs/changes/CHANGELOG.md
- packages/chevrotain/docs/guide/resolving_grammar_errors.md
- packages/chevrotain/src/parse/parser/traits/recognizer_engine.ts
- packages/chevrotain/test/parse/recognizer/infinite_loop_spec.ts
- yarn.lock
> Better handling of infinite loops in repetitions.

- packages/chevrotain/api.d.ts
> Add type overload for RULE to enable typing embedded actions

- .idea/chevrotain.iml
- packages/chevrotain/api.d.ts
- packages/chevrotain/benchmark_web/parsers/options.js
- packages/chevrotain/docs/features/position_tracking.md
- packages/chevrotain/docs/guide/performance.md
- packages/chevrotain/src/parse/cst/cst.ts
- packages/chevrotain/src/parse/parser/parser.ts
- packages/chevrotain/src/parse/parser/traits/tree_builder.ts
- packages/chevrotain/test/parse/cst_spec.ts
- packages/chevrotain/test/parse/recognizer/recognizer_config_spec.ts
- packages/chevrotain/test/utils/matchers.ts
Try to add location information on CstNodes
Close #932
> implement logic to compute node location information

- packages/chevrotain/chevrotain-master.js
- packages/chevrotain/src/parse/parser/traits/lexer_adapter.ts
- packages/chevrotain/test/api_spec.js
- packages/chevrotain/test/parse/cst_spec.ts
- packages/chevrotain/test/parse/grammar/checks_spec.ts
- packages/chevrotain/test/parse/grammar/interperter_spec.ts
- packages/chevrotain/test/parse/predicate_spec.ts
- packages/chevrotain/test/parse/recognizer/infinite_loop_spec.ts
- packages/chevrotain/test/parse/recognizer/rules_override_spec.ts
- packages/chevrotain/test/parse/recognizer_lookahead_spec.ts
- packages/chevrotain/test/parse/recognizer_spec.ts
> Detect missing "performSelfAnalysis" during a parser's input setter.

- packages/chevrotain/api.d.ts
- packages/chevrotain/src/parse/exceptions_public.ts
- packages/chevrotain/test_integration/definitions/api_type_checking.ts
> fix #990: declare parsing exceptions as classes

- packages/chevrotain/api.d.ts
> Remove optional modifier for CustomPatternMatcherFunc parameters

- packages/chevrotain/api.d.ts
- packages/chevrotain/docs/.vuepress/config.js
- packages/chevrotain/docs/guide/resolving_grammar_errors.md
- packages/chevrotain/src/parse/errors_public.ts
- packages/chevrotain/src/parse/grammar/checks.ts
- packages/chevrotain/src/parse/grammar/gast/gast_public.ts
- packages/chevrotain/src/parse/parser/parser.ts
- packages/chevrotain/src/parse/parser/traits/gast_recorder.ts
- packages/chevrotain/test/full_flow/backtracking/backtracking_parser.ts
- packages/chevrotain/test/parse/grammar/checks_spec.ts
- packages/chevrotain/test/parse/recognizer_lookahead_spec.ts
> Improved handling alternatives ambiguities

- packages/chevrotain/api.d.ts
- packages/chevrotain/test/full_flow/ecma_quirks/ecma_quirks.ts
- packages/chevrotain/test/scan/lexer_errors_public_spec.ts
> De-optionalize IToken.tokenType

- .idea/.gitignore
- .idea/runConfigurations/compile.xml
- .idea/runConfigurations/compile_watch.xml
- .idea/runConfigurations/coverage.xml
- packages/chevrotain/api.d.ts
- packages/chevrotain/docs/changes/CHANGELOG.md
- packages/chevrotain/src/scan/lexer.ts
- packages/chevrotain/src/scan/lexer_public.ts
- packages/chevrotain/src/scan/reg_exp.ts
- packages/chevrotain/test/scan/first_char_spec.ts
- packages/chevrotain/test/scan/perf_tracer_spec.ts
- Perf Tracing during Lexer Initilization.
- Optimize initilization performance for RegExps that may start with many possible characters, e.g:
- Reduced CSS Lexer init time by ~30%.
> Lexer Init upgrades

- packages/chevrotain/docs/features/gates.md
- packages/chevrotain/docs/features/grammar_inheritance.md
- packages/chevrotain/docs/guide/performance.md
- packages/chevrotain/docs/guide/resolving_lexer_errors.md
- packages/chevrotain/docs/guide/syntactic_content_assist.md
- packages/chevrotain/docs/tutorial/step3b_adding_actions_embedded.md
- packages/chevrotain/docs/tutorial/step4_fault_tolerance.md
@bd82 - Take a look at my proposed doc changes, as discussed on Gitter, and let me know if you have any requested changes or other questions.
Added additional documentation for using GATE with the LA method
Added additional information for setting start_chars_hint
Fixed various spelling errors
> Doc updates

- packages/chevrotain/api.d.ts
- packages/chevrotain/src/parse/cst/cst_visitor.ts
- packages/chevrotain/src/parse/parser/traits/gast_recorder.ts
- packages/chevrotain/src/parse/parser/traits/recognizer_api.ts
- packages/chevrotain/src/parse/parser/traits/recognizer_engine.ts
- packages/chevrotain/src/scan/lexer_errors_public.ts
- packages/chevrotain/test/parse/cst_spec.ts
- packages/chevrotain/test/parse/cst_visitor_spec.ts
- packages/chevrotain/test/parse/traits/perf_tracer_spec.ts
Fixed #970
@bd82 sorry for the delay :)
> Fix type safety with OR() rules

- packages/chevrotain/docs/changes/CHANGELOG.md
- packages/chevrotain/src/parse/grammar/interpreter.ts
- packages/chevrotain/test/parse/recognizer/infinite_loop_spec.ts
> fix: empty alts inside nested repetitions cause infinite loop

- packages/chevrotain/docs/changes/CHANGELOG.md
- packages/chevrotain/src/lang/lang_extensions.ts
> fix: runtime errors after webpack minification

- packages/chevrotain/docs/guide/resolving_lexer_errors.md
- packages/chevrotain/docs/guide/syntactic_content_assist.md
- packages/chevrotain/docs/tutorial/step4_fault_tolerance.md
Just a few small improvements to the guide/tutorial.
> docs: minor corrections

- packages/website/docs/tutorial/step1_lexing.md
There's an in valid link in `step1_lexing` - this fixes the link :slightly_smiling_face:
> Fix dead link in docs

- packages/chevrotain/src/parse/errors_public.ts
> docs: fix outdated wikipedia reference

- packages/cst-dts-gen/scripts/update-snapshots.js
- packages/cst-dts-gen/src/generate.ts
- packages/cst-dts-gen/src/model.ts
- packages/cst-dts-gen/test/snapshots/alternation_label/input.ts
- packages/cst-dts-gen/test/snapshots/alternation_label/output.d.ts
- packages/cst-dts-gen/test/snapshots/alternation_label/sample_spec.ts
> Correctly generate CST type definitions for alternations with labels

- packages/chevrotain/src/parse/parser/traits/recoverable.ts
> Consider token categories during re-sync

- packages/chevrotain/src/parse/parser/traits/recoverable.ts
- packages/chevrotain/test/full_flow/error_recovery/switch_case/switchcase_recovery_parser.ts
- packages/chevrotain/test/full_flow/error_recovery/switch_case/swithcase_recovery_spec.ts
- packages/types/api.d.ts
- packages/website/docs/tutorial/step4_fault_tolerance.md
> Allow to overwrite if token can be deleted in recovery mode

- packages/chevrotain/src/parse/parser/traits/recoverable.ts
As discussed here https://github.com/Chevrotain/chevrotain/pull/1754#discussion_r795633873
> Explicit return type of canTokenTypeBeInsertedInRecovery

- packages/types/api.d.ts
@msujew please have a look at this approach to reduce redundancy in class X implements Y syntax.
> refactor: less duplication in lookahead apis
